# -*- coding: utf-8 -*-
"""ACD(toddler).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QdAEW92hbHgQCpsU6vRPfp9Xjpustser
"""

from google.colab import drive
drive.mount('/content/gdrive',force_remount=True)

import pandas as pd
data = pd.read_csv('/content/gdrive/MyDrive/Toddler Autism dataset.csv')

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import HistGradientBoostingClassifier


# Load the dataset
data = pd.read_csv('/content/gdrive/MyDrive/Toddler Autism dataset.csv')

# Data preprocessing
le = LabelEncoder()
for column in data.columns:
    if data[column].dtype == type(object):
        data[column] = le.fit_transform(data[column])

# Split the data into features and target

X = data.drop('Class/ASD ', axis=1)
y = data['Class/ASD ']


# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize classifiers
models = {
    "SVM": SVC(),
    "Naive Bayes": GaussianNB(),
    "Random Forest": RandomForestClassifier(),
    "KNN": KNeighborsClassifier()
}

from sklearn.impute import SimpleImputer
import numpy as np

# Impute missing values with the median
imputer = SimpleImputer(missing_values=np.nan ,strategy='median')

# Fit the imputer on the training data
imputer.fit(X_train)

# Transform both training and test data
X_train = imputer.transform(X_train)
X_test = imputer.transform(X_test)


# Train and evaluate each model
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print(f"Model: {name}")
    print(f"Accuracy: {accuracy}")
    print(f"Classification Report:\n{classification_report(y_test, y_pred)}")
    print("="*50)


# Load the dataset
data = pd.read_csv('/content/gdrive/MyDrive/Toddler Autism dataset.csv')


# Data preprocessing
le = LabelEncoder()
for column in data.columns:
    if data[column].dtype == type(object):
        data[column] = le.fit_transform(data[column])

# Split the data into features and target
X = data.drop('Class/ASD ', axis=1)
y = data['Class/ASD ']

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the model
selected_model = HistGradientBoostingClassifier()

# Train the model on the entire dataset
selected_model.fit(X_train, y_train)

# Ensure consistent feature names between training and prediction data
X_test = X_test.rename(columns={'Class/ASD ': 'Class_ASD '})

# Predict whether the person has ASD or not
prediction = selected_model.predict(X_test)

# Interpret the prediction
if prediction[0] == 1:
    print("The person is likely suffering from ASD.")
else:
    print("The person is not likely suffering from ASD.")

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(8, 6))
sns.heatmap(pd.crosstab(y_test, y_pred), annot=True, cmap='Blues', fmt='g')
plt.title(f"Confusion Matrix - {name}")
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

# Plotting distribution of predicted values
plt.figure(figsize=(10, 6))
sns.histplot(y_pred, kde=True, color='skyblue')
plt.title('Distribution of Predicted Values')
plt.xlabel('Predicted Class')
plt.ylabel('Frequency')
plt.show()

from sklearn import metrics
roc_curves = {}
# Visualize ROC curves
plt.figure(figsize=(10, 8))
for name, curve_data in roc_curves.items():
    plt.plot(curve_data['fpr'], curve_data['tpr'], label=f"{name} (AUC = {curve_data['roc_auc']:.2f})")

plt.plot([0, 1], [0, 1], linestyle='--', color='gray', label='Random Guess')
plt.title('ROC Curves')
plt.xlabel('False Positive Rate (FPR)')
plt.ylabel('True Positive Rate (TPR)')
plt.legend()
plt.grid(True)
plt.show()